In [1]:
import pandas as pd
import yfinance as yf

In [2]:
start = "2026-01-01"
end = "2026-01-15"
stock = ["AAPL", "TSLA"]

data = yf.download(stock, start=start, end=end)

[*********************100%***********************]  2 of 2 completed

In [3]:
data

Price            Close                    High                     Low  \
Ticker            AAPL        TSLA        AAPL        TSLA        AAPL
Date
2026-01-02  270.756653  438.070007  277.580254  458.339996  268.748522
2026-01-05  267.010162  451.670013  271.256189  457.549988  265.891214
2026-01-06  262.114716  432.959991  267.299866  448.250000  261.874950
2026-01-07  260.086609  431.410004  263.433483  438.369995  259.567106
2026-01-08  258.797852  435.799988  259.047618  436.890015  255.460962
2026-01-09  259.127533  445.010010  259.966744  449.049988  255.980484
2026-01-12  260.006714  448.959991  261.055720  454.299988  256.559927
2026-01-13  260.805939  447.200012  261.565238  451.809998  258.148452
2026-01-14  259.716980  439.200012  261.575257  443.910004  256.470018

Price                         Open                Volume
Ticker            TSLA        AAPL        TSLA      AAPL      TSLA
Date
2026-01-02  435.299988  272.005484  457.799988  37838100  85535400
2026-01-05  444.570007  270.387007  447.989990  45647200  67940800
2026-01-06  428.779999  266.750392  446.380005  52352100  89093800
2026-01-07  431.290009  262.953951  435.899994  48309800  59828800
2026-01-08  424.369995  256.779720  427.890015  50419300  57041100
2026-01-09  430.390015  258.837796  435.950012  39997000  67331500
2026-01-12  438.000000  258.917736  441.230011  45263800  61649600
2026-01-13  443.950012  258.478130  450.200012  45730800  53719200
2026-01-14  434.220001  259.247418  442.809998  40019400  57259500

In [4]:
df = pd.DataFrame(data)
df.head()

Price            Close                    High                     Low  \
Ticker            AAPL        TSLA        AAPL        TSLA        AAPL
Date
2026-01-02  270.756653  438.070007  277.580254  458.339996  268.748522
2026-01-05  267.010162  451.670013  271.256189  457.549988  265.891214
2026-01-06  262.114716  432.959991  267.299866  448.250000  261.874950
2026-01-07  260.086609  431.410004  263.433483  438.369995  259.567106
2026-01-08  258.797852  435.799988  259.047618  436.890015  255.460962

Price                         Open                Volume
Ticker            TSLA        AAPL        TSLA      AAPL      TSLA
Date
2026-01-02  435.299988  272.005484  457.799988  37838100  85535400
2026-01-05  444.570007  270.387007  447.989990  45647200  67940800
2026-01-06  428.779999  266.750392  446.380005  52352100  89093800
2026-01-07  431.290009  262.953951  435.899994  48309800  59828800
2026-01-08  424.369995  256.779720  427.890015  50419300  57041100

In [5]:
df[df["Close"] > 260]

df["Close"].sort_values("TSLA", ascending=True)

Ticker            AAPL        TSLA
Date
2026-01-07  260.086609  431.410004
2026-01-06  262.114716  432.959991
2026-01-08  258.797852  435.799988
2026-01-02  270.756653  438.070007
2026-01-14  259.716980  439.200012
2026-01-09  259.127533  445.010010
2026-01-13  260.805939  447.200012
2026-01-12  260.006714  448.959991
2026-01-05  267.010162  451.670013

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
import warnings
warnings.filterwarnings("ignore")

In [7]:
start = "2026-01-01"
end = "2026-03-15"
stock = ["AAPL", "TSLA"]

data = yf.download(stock, start=start, end=end)

[*********************100%***********************]  2 of 2 completed

In [8]:
df = data.copy()
df.isnull().values.any()
df = df.dropna()

df.head()

Price            Close                    High                     Low  \
Ticker            AAPL        TSLA        AAPL        TSLA        AAPL
Date
2026-01-02  270.756653  438.070007  277.580254  458.339996  268.748522
2026-01-05  267.010162  451.670013  271.256189  457.549988  265.891214
2026-01-06  262.114716  432.959991  267.299866  448.250000  261.874950
2026-01-07  260.086609  431.410004  263.433483  438.369995  259.567106
2026-01-08  258.797852  435.799988  259.047618  436.890015  255.460962

Price                         Open                Volume
Ticker            TSLA        AAPL        TSLA      AAPL      TSLA
Date
2026-01-02  435.299988  272.005484  457.799988  37838100  85535400
2026-01-05  444.570007  270.387007  447.989990  45647200  67940800
2026-01-06  428.779999  266.750392  446.380005  52352100  89093800
2026-01-07  431.290009  262.953951  435.899994  48309800  59828800
2026-01-08  424.369995  256.779720  427.890015  50419300  57041100

In [ ]:
df1 = df[(df["Volume"]["TSLA"] > 50000000) & (df["Volume"]["TSLA"] < 70000000)]

df1["Volume"].head(10).min(numeric_only=True)

Ticker
AAPL    39997000
TSLA    53719200
dtype: int64